### ISSUE TITLE
Fails to compile with the recent vulkan-hpp bindings

### ISSUE THREAD

**Issue by ijn-yamato** [YaaZ/VulkanMemoryAllocator-Hpp#1]
Both the bindings found in this repository and the bindings generated manually via the script (VMA version 3.0.1-development) fail to compile on a fairly recent version of the Vulkan headers (version 1.3.211). It's possible it has been happening so for some older versions, but I haven't tested that.

Test program:
```cpp
#include <vulkan/vulkan.hpp>
#include "vma/vk_mem_alloc.hpp"

void dosmth(vma::Allocation&) {
    // trick the compiler into thinking that the allocation is used
}

int main() {
    return 0;
}
```

My environment:
- OS: Arch Linux x86_64
- `vulkan-headers` version: 1:1.3.211-1

[Build log](https://github.com/YaaZ/VulkanMemoryAllocator-Hpp/files/8495574/build_log.txt)

**Comment by JnCrMx** [comment]
Seems to be caused by https://github.com/KhronosGroup/Vulkan-Hpp/commit/a8d47f46 which removes the 2 parameter version of ``createResultValue`` in favor of ``resultCheck`` and ``createResultValueType``.

See https://github.com/KhronosGroup/Vulkan-Hpp/commit/a8d47f46#diff-898cb0e7751b09c5d63a1837ed3b9a52a6ec4bb07f056f45b0bc3efc26db8e63L1033 for a diff of ``Device::bindBufferMemory``:
```diff
@@ -1030,9 +1045,10 @@ namespace VULKAN_HPP_NAMESPACE
   {
     VULKAN_HPP_ASSERT( d.getVkHeaderVersion() == VK_HEADER_VERSION );

-    Result result = static_cast<Result>(
-      d.vkBindBufferMemory( m_device, static_cast<VkBuffer>( buffer ), static_cast<VkDeviceMemory>( memory ), static_cast<VkDeviceSize>( memoryOffset ) ) );
-    return createResultValue( result, VULKAN_HPP_NAMESPACE_STRING "::Device::bindBufferMemory" );
+    VkResult result =
+      d.vkBindBufferMemory( m_device, static_cast<VkBuffer>( buffer ), static_cast<VkDeviceMemory>( memory ), static_cast<VkDeviceSize>( memoryOffset ) );
+    resultCheck( static_cast<VULKAN_HPP_NAMESPACE::Result>( result ), VULKAN_HPP_NAMESPACE_STRING "::Device::bindBufferMemory" );
+    return createResultValueType( static_cast<VULKAN_HPP_NAMESPACE::Result>( result ) );
   }
 #endif /*VULKAN_HPP_DISABLE_ENHANCED_MODE*/
```
