### ISSUE TITLE
Automatically fetch VulkanFunctions from VULKAN_HPP_DEFAULT_DISPATCHER

### ISSUE THREAD

**Issue by Qwinci** [YaaZ/VulkanMemoryAllocator-Hpp#11]
In vma::Allocator constructor maybe check if `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC == 1` and if it is then automatically construct vma::VulkanFunctions using function pointers in VULKAN_HPP_DEFAULT_DISPATCHER.

**Comment by YaaZ** [comment]
It's hard to generate such code, because it may need to know, which functions correspond to instance/device and also deal with KHR/VK1.1 functions, so I just added a handwritten utility function.
```
vma::functionsFromDispatcher(someDispatcher);
vma::functionsFromDispatcher(); // Default
vma::functionsFromDispatcher(instance.getDispatcher(), device.getDispatcher()); // RAII
```
