### ISSUE TITLE
Updating Vulkan hpp and VMA

### ISSUE THREAD

**Issue by matt328** [YaaZ/VulkanMemoryAllocator-Hpp#17]
I'm wondering how to update these bindings for newer versions of Vulkan hpp and VMA.  I guess my first question is are the bindings 100% generated at this point, or are there additions made by hand after generation?

I'm curious about this because I'm starting a new project and want to use v1.3.231.0 of the Vulkan SDK as it fixes a C++20 issue I was having with Vulkan hpp.  As it stands now, there are tons of compiler warnings and errors and overall flakiness if the versions are mismatched (like you said would happen).

If there is nothing handwritten at this point, would you be interested in publishing multiple versions in vcpkg (possibly matching the version number of the Vulkan SDK), or at the very least, tagging them in this repo?  In the meantime I'll play around with the java files in the repo and see where I get.

**Comment by matt328** [comment]
Answering my own question here, a) it looks like only the `vk_mem_alloc.hpp` file is handwritten, the others are generated.  b) I was able to regenerate the rest of the hpp files using the java tool in the repo, and specifying the commit sha for vulkan sdk 1.3.231 and vma 3.0.1.  Although git doesn't show any differences in the files, the 'updated' files don't have any errors and flakiness I was seeing before.

Aside, has this been removed from vcpkg?  I can't seem to find it.

**Comment by YaaZ** [comment]
Yes, only `vk_mem_alloc.hpp` is handwritten and all other files are generated. That's weird though, that you've got errors with the committed headers which are gone when you generated them locally. Vulkan-Hpp revision doesn't affect generated files in any way, only VMA does, it was already generated for v3.0.1, so I don't understand why it failed, especially given that git shows no difference, as you said.

And regarding vcpkg, I have never used it and have no idea, what's going on there. It was published by a user, not by me btw: #16

**Comment by matt328** [comment]
It's entirely possible it was late and mistakes were made.  I'm pretty sure all the errors were me accidentally copying something that wasn't copyable, as that error message is pretty verbose.  I wonder if the author of #16 knows anything about why it's not visible in vcpkg yet.

**Comment by McFlyboy** [comment]
Hi @matt328. I'm the author of the vcpkg port for this repo. I am not sure why the port isn't visible, but it is still available by adding `"vulkan-memory-allocator-hpp"` to `dependencies` in your vcpkg manifest file. I will see if I can figure out how to make it visible 🙂

**Comment by McFlyboy** [comment]
@matt328 Looks like the search results on the vcpkg.io page is just outdated. None of the other ports that were added in the newest release is searchable either. I assume it will become visible/searchable once Microsoft decides to update the webpage 😅

**Comment by YaaZ** [comment]
OK I guess this can be closed
