### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Latias94** [YaaZ/VulkanMemoryAllocator-Hpp#22]
Vulkan-Hpp v1.3.234 introduces a pr https://github.com/KhronosGroup/Vulkan-Hpp/pull/1438 which break the compilation with VulkanMemoryAllocator-Hpp.
According to this issue: https://github.com/KhronosGroup/Vulkan-Hpp/issues/1501 , do you have time to modify the related flags?

**Comment by Latias94** [comment]
Ok, i have just check https://github.com/YaaZ/VulkanMemoryAllocator-Hpp/issues/18 , can you provide a new release with these changes.

**Comment by YaaZ** [comment]
Done.
