### ISSUE TITLE
Allow optional usage of vulkan module

### ISSUE THREAD

**Issue by Stef-2** [YaaZ/VulkanMemoryAllocator-Hpp#29]
Given that [vulkan-hpp](https://github.com/KhronosGroup/Vulkan-Hpp) now offers a module unit instead of a set of traditional header files, it would be very useful if either [vma-hpp](https://github.com/YaaZ/VulkanMemoryAllocator-Hpp) could do the same, or perhaps provide a ``DEFINE`` that would utilize the vulkan module over its very lengthy headers, as this can drastically reduce compile times.

**Comment by Arthapz** [comment]
or better, provide a vma C++ module

**Comment by YaaZ** [comment]
Please take a look and let me know how does it work for you.
