### ISSUE TITLE
Make c++20 module use vulkan_hpp module

### ISSUE THREAD

**Issue by qbojj** [YaaZ/VulkanMemoryAllocator-Hpp#33]
Currently `vk_mem_alloc.cppm` includes `vk_mem_alloc.hpp` which in turn includes `<vulkan/vulkan.hpp>`, but it could import the `vulkan_hpp` module, as if you are using vma-hpp as module you are probably also using vulkan-hpp as a module.

**Comment by YaaZ** [comment]
Not sure I got your idea. How could we import `vulkan_hpp`, **instead of** including `<vulkan/vulkan.hpp>` in `vk_mem_alloc.hpp`?

**Comment by qbojj** [comment]
IDK if it is legal, by You could try 
```c++
#ifdef VMA_USE_VULKAN_MODULE
import vulkan_hpp;
#else
#include <...>
#endif
```

I have posted it as a possibility and hadn't thought if it even is possible.

**Comment by qbojj** [comment]
My bad... I cannot read. That only refers to `pp-import` so, only to the imports of header modules
