### ISSUE TITLE
Duplicate symbol `void __cdecl vma::detail::resultCheck(enum vk::Result, char const *)`

### ISSUE THREAD

**Issue by ivirtex** [YaaZ/VulkanMemoryAllocator-Hpp#49]
It seems like #43 has broken builds for me, due to the `vma::detail::resultCheck` defined directly in the header `vk_mem_alloc.hpp`.

**Comment by walkiewicz125** [comment]
I mention this in 
https://github.com/YaaZ/VulkanMemoryAllocator-Hpp/issues/48
