### ISSUE TITLE
vk_mem_alloc.h should be optional

### ISSUE THREAD

**Issue by Nahor** [YaaZ/VulkanMemoryAllocator-Hpp#6]
To avoid risk of conflicts with other projects/code hierarchy/..., and confusing IDEs, `vk_mem_alloc.h` shouldn't be in the baseline include directory. This is especially true now that Vulkan SDK ships with VMA (as of 1.3.216)

I understand that for practical purpose, it might be convenient to have `vk_mem_alloc.h` shipped with vma-hpp, but at the very least it ought to be in its own directory so that the application developer can choose to use the header shipped with vma-hpp or some other one (Vulkan SDK, submodule, ...)

Also worth noting is that in the case of the SDK (1.3.216 for Windows at least), the vma header is in a `vma` subdirectory. It would be best if vma-hpp could handle different location like that. (Alternatively the application project can add `<VK_SDK>/include/vma` as an include path, but it's not as clean IMHO)

**Comment by tomix1024** [comment]
Regarding the inclusion of the `vk_mem_alloc.h`, I think that it does make sense to include the header with vma-hpp, since the hpp headers are generated for a particular version of the C implementation.

At least on my system, the `vk_mem_alloc.h` that ships with the LunarG SDK is placed straight into `/usr/include`.

**Comment by Nahor** [comment]
One can just download the tagged version of vma-hpp that matches the version provided by the SDK/submodules/whatever

And I'm not suggesting to not provide the vma header, just that it be in a separate directory from the vma-hpp headers, so that one can choose which vma header to use. Currently one has no choice.

> At least on my system, the vk_mem_alloc.h that ships with the LunarG SDK is placed straight into /usr/include.

Then all the more reasons to have a configurable prefix :). For me, I'm using the SDK for Windows. There are no headers files directly in `<SDK>/include`, all headers are in one subdirectory or another.
![image](https://user-images.githubusercontent.com/1198364/174138169-23fc98a8-790c-4e41-8753-e6d7e2090549.png)

**Comment by YaaZ** [comment]
`vk_mem_alloc.h` was placed here for convenience, I don't see any point to move it into another directory, as one can just pull it from the submodule if needed, so I think it can just be deleted.

**Comment by YaaZ** [comment]
Now it's included via `#include <vk_mem_alloc.h>`, if one needs more control, specific VMA can be included manually before VMA-Hpp.
