### ISSUE TITLE
[Request] Unique handles

### ISSUE THREAD

**Issue by shinjitumala** [YaaZ/VulkanMemoryAllocator-Hpp#7]
Hi.

Is it possible to get the code generators to generate unique handles like in `vulkan.hpp`?
For example, `alloc.createBufferUnique(...)` where `alloc` is a `vma::Allocator`.

**Comment by shinjitumala** [comment]
I just tried to add them myself but just realized that it's not very straightforward to generate unique handles where vma returns pairs.

For example, the function 'vma::Allocator::createBuffer(..)' returns a pair that has to be deleted together.

Any ideas? Or is just a bad idea to add unique handles in vma?

**Comment by YaaZ** [comment]
Sure it's a good idea. But I believe they are not necessarily destroyed together (vmaDestroyBuffer = vkDestroyBuffer + vmaFreeMemory), so I think we can just return a pair of unique handles in that case.

**Comment by shinjitumala** [comment]
I see.

I'm still very new to VMA, so I guess I'll give myself more time to understand it.
